-- AlterTable
ALTER TABLE "Table" ADD COLUMN     "posX" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "posY" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "shape" TEXT NOT NULL DEFAULT 'square';
